# Generated by Django 4.0.5 on 2022-06-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Meeting', 'Meeting')], max_length=20),
        ),
    ]
